services:
  web:  # Streamlitアプリ用サービス
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    env_file:
      - .env

  db:  # PostgreSQL用サービス
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # 初期データ投入

volumes:
  pgdata: